sig-release:
  sig-release-master-blocking:
    ci-kubernetes-e2e-gci-gce:
      - 31582
  sig-release-1.12-all:
    ci-kubernetes-e2e-gce-cos-k8sbeta-default:
      - 6808
  sig-release-1.11-all:
    ci-kubernetes-e2e-gce-cos-k8sstable1-default:
      - 4267
  sig-release-1.10-all:
    ci-kubernetes-e2e-gce-cos-k8sstable2-default:
      - 1446
  sig-release-1.9-all:
    ci-kubernetes-e2e-gce-cos-k8sstable3-default:
      - 370
conformance:
  conformance-gce:
    ci-kubernetes-gce-conformance:
      - 827
    ci-kubernetes-gce-conformance-stable-1-12:
      - 3
      - 84
    ci-kubernetes-gce-conformance-stable-1-11:
      - 251
    ci-kubernetes-gce-conformance-stable-1-10:
      - 746
    ci-kubernetes-gce-conformance-stable-1-9:
      - 747
    ci-kubernetes-gce-conformance-stable-1-8:
      - 561
