# docker-compose.yml
# #+NAME: hasura docker-compose

# hasura/docker-compose.yaml
version: "3.7"

services:
 hasura:
    #image: hasura/graphql-engine:v1.0.0-beta.3
    # append '.cli-migrations' to auto run 'hasura migrations apply'
    container_name: "${USER}-hasura"
    image: hasura/graphql-engine:v1.0.0-beta.4.cli-migrations
    restart: always
    networks:
      - web
    environment:
      # Should try and set database be read only for public
      #- HASURA_GRAPHQL_DATABASE_URL=postgres://non-priv-user@172.17.0.1:5432/database-name
      #- HASURA_GRAPHQL_DATABASE_URL=postgres://non-priv-user@172.17.0.1:5432/$OUTER-USER
      # https://docs.docker.com/compose/compose-file/#variable-substitution
      # https://docs.docker.com/compose/env-file/
      - "HASURA_GRAPHQL_DATABASE_URL=postgres://${USER}@172.17.0.1:5432/${USER}"
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
    volumes:
      - ./migrations:/hasura-migrations
    expose:
      - "8080"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.port=8080"
      - "traefik.basic.protocol=http"
      - "traefik.basic.frontend.rule=Host:${USER}-hasura.sharing.io"
#volumes:
#  migrations:
networks:
  web:
    external: true
