apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
auditPolicy:
  path: "/config/audit-policy.yaml"
  logDir: "/config"
  logMaxAge: 10
  webhookConfigPath: "/config/webhook-config.yaml"
  webhookInitialBackoff: "50s"
featureGates:
  Auditing: true
