apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# resources:
#   - basic-auth.yaml
# bases:
#   - ../tilt
  # - ../hasura
  # - ../pgadmin
# patchesJson6902:
#   - target:
#       group: extensions
#       version: v1beta1
#       kind: Ingress
#       name: tilt-ingress
#     path: patch-ingress.yaml
  # - target:
  #     group: extensions
  #     version: v1beta1 
  #     kind: Ingress
  #     name: hasura-ingress
  #   path: patch-ingress.yaml
  # - target:
  #     group: extensions
  #     version: v1beta1 
  #     kind: Ingress
  #     name: pgadmin-ingress
  #   path: patch-ingress.yaml
