apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - certs.yaml
bases:
  - ../../apps/webapp/deployment
patchesJson6902:
  - target:
      group: extensions
      version: v1beta1 
      kind: Ingress
      name: webapp-ingress
    path: patch-ingress-certs.yaml
